#!/bin/bash

source ~/.bfos/bin/bf_alias_and_functions
source ~/.bfos/resources/ps1
source ~/.bfos/bin/greeting

export PATH="$PATH:~/.bfos/system/node_modules/.bin"
export PATH="$PATH:~/.bfos/bin"
export PATH="$PATH:~/.bfos/system/modules/tools"
